// This file is generated

I_birth_place_0 = [
"Surry, Colony of Virginia, British Colonial America",
"Lancaster, PA, Little Britain",
"England, United Kingdom",
"Scotland",
"Virginia, British Colonial America",
"Gloucester, Virginia, British Colonial America",
"Shropshire, England",
"Sothenge, Yorkshire, England",
"Reigate, Surrey, England",
"Prees, Shropshire, England",
"Coleshill, Warwickshire, England",
"Coleshill, Warwickshire, England",
"Killeen, Meath, Ireland",
"Jefferson County, TN",
"Hartford, Connecticut",
"Bierzwienna D\u0142uga, Kolo, Wielkopolska, Poland",
"Bierzwienna D\u0142uga, Wielkopolska, Poland",
"Bierzwienna D\u0142uga, Wielkopolska, Poland",
"BIerzwienna Dluga, Wielkopolskie, Poland",
"Pyzdry, Wrzesnia, Wielkopolski, Poland",
"Hartford, Connecticut",
"Woonsocket, Rhode Island",
"Corca Loighodhe, West Cork, Eire",
"South Carolina, United States",
"Virginia, British Colonial America",
"Buncome, North Carolina, United States",
"Surry, Colony of Virginia, British Colonial America",
"Anson, Richmond, North Carolina",
"Cobham, Kent, England",
"",
"Aurarua, Lumpkin Georgia",
"",
"Caryville, TN",
"Rushcliffe, Nottinghamshire, England, United Kingdom",
"Gotham, Nottinghamshire, England",
"Desmond, Cork, Ireland",
"Annapolis, Anne Arundel, Maryland, British Colonial America",
"Georgetown, Kent, Maryland, British Colonial America",
"Middlesex, Virginia, British Colonial America",
"Virginia, British Colonial America",
"Wojtostwo, Pozan, Wielkopolskie, Poland",
"New Castle, Henry Castle, Kentucky",
"Kentucky",
"Corca Laidhe, Munster, Ireland",
"Mobberley, Cheshire, England",
"Cheshire, England",
"Chester, Pennsylvania, British Colonial America",
"Wilmslow, Cheshire, England",
"Wilmslow, Cheshire, England",
"Lancaster, PA",
"Union, USA",
"",
"Little Britain Township, Lancaster, Pennsylvania, British Colonial America",
"Hartshorne, South Derbyshire district, Derbyshire, England, United Kingdom",
"Germantown, Pennsylvania, British Colonial America",
"Derby, Derby district, Derbyshire, England, United Kingdom",
"Kentucky",
"Caroline, Virginia, United States",
"Grant, Kentucky, United States",
"County Meath, Ireland",
"Dublin, County Dublin, Ireland",
"County Meath, Ireland",
"Canterbury, Kent, England",
"Canterbury, Kent, England",
"Barham, Kent, England",
"Hampton, Elizabeth City, Virginia, British Colonial America",
"Maryland, British Colonial America",
"Loudoun, Virginia, United States",
"Laurel, Kentucky, United States",
"Cocke, Tennessee, United States",
"London, Kentucky",
"Hackleton, Northamptonshire, England",
"Georgetown, Kent, Maryland, United States",
"Georgetown, Kent, Maryland, British Colonial America",
"Hartshorne, South Derbyshire district, Derbyshire, England, United Kingdom",
"Merionethshire, Wales",
"Llangefni, Anglesey, Gwynedd, Wales, United Kingdom",
"Eastwell, Kent, England",
"Kildare, Leinster, Ireland",
"Kildrought, County Kildare, Leinster, Ireland",
"Kildare, Leinster, Ireland",
"Kildare, Leinster, Ireland",
"Harristown, County Kildare, Ireland",
"",
"Cork, Ireland",
"Coleshill, Warwickshire, England",
"",
"Bratucice, Bechnia, Poland",
"",
"Cornhill, London, England",
"Laurel, Kentucky, United States",
"Laurel, Kentucky, United States",
"Laurens, South Carolina",
"Bishopbourne, Kent, England",
"Coventry, Warwickshire, England",
"Coventry, Warwickshire, England",
"Harlan, Kentucky, United States",
"Radnorshire, Powys, Wales, United Kingdom",
"Wales",
"",
"",
"Dorset, England, UK",
"South Newington, Cherwell district, Oxfordshire, England",
"Buncome, North Carolina, United States",
"North Carolina, United States",
"Surry, Colony of Virginia, British Colonial America",
"Mars Hill, Madison, North Carolina",
"King and Queen, Virginia, British Colonial America",
"",
"Laurens, South Carolina",
"Granville, North Carolina",
"Pittsylvania, Virginia",
"Yancey, North Carolina, United States",
"North Carolina, United States",
"Cornhill, London, England",
"Cornhill, London, England",
"Wiltshire, England",
"North Farnham, Richmond, Virginia, United States",
"Haxleston, Staffordshire, England",
"Harton, Durham, England",
"Marsh Gibbon, Buckinghamshire, England",
"Marsh Gibbon, Buckinghamshire, England",
"Kentucky, British Colonial America",
"Sussex, England",
"Borzeciczki, Wielkopolskie, Poland",
"Ireland",
"Canterbury, Kent, England",
"St. James Northam Parish, Goochland, Virginia, Kingdom of Great Britain",
"Virginia, British Colonial America",
"Mobberley, Cheshire, England",
"Munster, Ireland",
"Lough Lein, County Kerry, Ireland",
"Munster, Ireland",
"",
"Carberry, Ireland",
"Kilbrittain Castle, County Cork, Ireland",
"",
"County Kerry, Ireland",
"Virginia",
"Ireland",
"Knockareny, Kerry, Ireland",
"Franklin, Kentucky, United States",
"Henry, Kentucky, United States",
"Virginia",
"",
"",
"Henry, Kentucky",
"",
"",
"",
"San Francisco, CA",
"Cincinnati, Ohio",
"Texas, US",
"Lexington, Kentucky",
"",
"Ireland",
"Ireland",
"Knox, Tennessee, United States",
"Yorkshire, England",
"Prince George, Virginia, British Colonial America",
"Virginia, British Colonial America",
"Carolina, Marion, Virginia, United States",
"Virginia, British Colonial America",
"Cambridge, Gloucestershire, England",
"England",
"Donagal, Dundee, Ireland",
"Oldham, Lancashire, England",
"Bierzwienna D\u0142uga, Wielkopolska, Poland",
"",
"Virginia, British Colonial America",
"Lawne's Creek Parish, Isle of Wright, Virginia",
"Surry, Colony of Virginia, British Colonial America",
"Woodplumpton, Preston district, Preston district, Lancashire, England",
"England",
"Ludlow, Shropshire, England",
"",
"St. James Northam Parish, Goochland, Virginia, Kingdom of Great Britain",
"Munster, Ireland",
"Cork, Ireland",
"Cork, Ireland",
"Desmond, Cork, Ireland",
"",
"Cork, Ireland",
"Desmond, Cork, Ireland",
"Ireland",
"Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Nass, County Kildare, Ireland",
"Ireland",
"Desmond, Cork, Ireland",
"Ireland",
"County Kerry, Ireland",
"Cork, Ireland",
"Kinealmeaky, Cork, Ireland",
"Kinealmeaky, Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Desmond, Cork, Ireland",
"Ireland",
"Desmond, Cork, Ireland",
"Munster, Ireland",
"Ireland",
"Ireland",
"",
"",
"Dunboy Castle, County Cork, Ireland",
"Upper Parish, Nasemond, Virginia",
"Dublin, Leinster Province, Ireland",
"South Carolina, United States",
"Cy, Orangeburg, South Carolina",
"Ireland",
"Ireland",
"Munster, Ireland",
"Munster, Ireland",
"Ireland",
"",
"Kirkburton, Yorkshire, England",
"Lancashire, England",
"Oldham, Lancashire, England",
"Lancashire, England",
"Hartford, Connecticut",
"CT",
"Libau, Russia",
"Wrockwardine, Shropshire, England",
"Prees, Shropshire, England",
"Middlesex, Virginia, British Colonial America",
"Shropshire, England",
"York, Virginia, British Colonial America",
"Harrow, Middlesex, England",
"Ludlow, Shropshire, England",
"Wrotham, Kent, England",
"Wellington, Shropshire, England",
"Sabanagrande, Francisco Moraz\u00e1n, Honduras",
"",
"Nacaome, Valle, Honduras",
"",
"Henrico, Colony of Virginia, British Colonial America",
"Birmingham, Warwickshire, England",
"Germany",
"Campbell, TN",
"Kentucky",
"Fayette, Virginia, United States",
"Espana",
"San Lorenzo, Valle, Honduras",
"Castle Donnington, Leicestershire, England",
"of Duddington, (now Wash., DC), Prince George, MD",
"Port Tobacco, Charles, Maryland, British Colonial America",
"",
"Bierzwienna D\u0142uga, Wielkopolska, Poland",
"",
"Berkshire, England",
"Limerick, Ireland",
"Limerick, Ireland",
"Walberton, Sussex, England",
"Ford Parish, Sussex, England",
"Samlesbury, Lancashire, England",
"Reigate, Surrey, England",
"Mexborough,  Yorkshire, England",
"Ulcombe, Kent, England",
"South Carolina, United States",
"Wilmslow, Cheshire, England",
"Middlesex, Virginia, British Colonial America",
"Middlesex, Virginia, British Colonial America",
"North Farnham, Richmond, Virginia, United States",
"Kentucky",
"Old Rappahannock, Virginia, British Colonial America",
"Caroline, Virginia, United States",
"St. James Northam Parish, Goochland, Virginia, Kingdom of Great Britain",
"Kostrzyn, Wielkopolskie, Poland",
"Wilmslow, Cheshire, England",
"Astbury, Cheshire, England",
"England",
"Huddersfield, Yorkshire, England",
"Arlington, Kent, England",
"England, United Kingdom",
"Arlington Castle, Kent, England",
"Mexborough,  Yorkshire, England",
"Arlington Castle, Kent, England",
"Arlington Castle, Kent, England"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
